### PR TITLE
Temp dir for making archive and moving them to backup dir

### PR DESCRIPTION
**Pull request by Spider84**
In my case backup stored at remote ftp server and I has changing script for making backups locally and then moving tar.gz to destination backup dir.

### CODE REVIEW

**Comment by tachtler** [comment]
Hi Alexey,

thank you for your contribution to dovecot-backup.sh.

A few questions:
- Shouldn't a file transfer be done completely in a following logic / script and not be mixed with the actual backup script?
 - Why are you prefer `/run` not `/tmp`? I think on **some (older) OS** `/run` does not exists?
 - Why are you prefer to create the backup-files locally and move them for every user direct after the creation to the (in your case) FTP directory (inside the for-loop). Maybe it could be better to create them all first and move all the backup-files at the end of the script with one last `mv` command? This could be better for a following logic for the file transfer **to store all or nothing** ?

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi Alexey,

unfortunately, I haven't heard from you in more than a week.

I would like to leave the logic as it is, because I think that the logic for the backup and one logic for the transfer of the backups should be separated, because the script, in my opinion, should not be responsible for all possible transfer variants.

Thank you!
Klaus.

**Comment by Spider84** [comment]
I received notification only now. Sorry.
In my case server use SSD disk. And I'm trying to minimise all write operations. So I use /run because it mounted to ram with tmpfs. 
Also I can't hold backups locally - for what? If I lose disk - lose all backups.

**Comment by tachtler** [comment]
Hi Alexey,

in your case, it make really sense, how you change the script.

I mean holding the backup locally only for that time. since they are **all** written to the local SSD and after that, move **all** backup files together to your final back destination.

Thank you!
Klaus.

**Pull request closed without merging**
