### PR TITLE
Added the option to run an incremental backup

### PR DESCRIPTION
**Pull request by CratlePeter**
Added a command 'incremental' to the script which, if found, sets up incremental backups.  If the command 'incrementalreset' is given then, effectively, a full backup is taken and the incremental state is set.  The intention is that users would schedule a 'incrementalreset' once a week and 'incremental' every other day.

If the command 'incremental' or 'incrementalreset' is not given then the script operates as it does today and creates a full backup.

It is not possible to mix a full backup (doveadm backup -f) with an incremental backup (doveadm backup -s)

### CODE REVIEW

**Comment by tachtler** [comment]
Hello CratlePeter,

first of all I want to thank you for participating in the further development of the dovecot_backup script.

But I am not quite sure if I want to go down this path. The option of incremental backups, which rely on runtime data from a previous sync, makes me a little uncomfortable.

The following is an excerpt from the Dovecot Wiki: [Doveadm-Sync](https://wiki.dovecot.org/Tools/Doveadm/Sync)

> Stateful synchronization (-s parameter) is the most efficient way to synchronize mailboxes. It relies on having the earlier dsync run's state saved somewhere and being passed to the next dsync run. Based on this state dsync can send only the changes that happened after the previous dsync run. As long as the state or the mailboxes aren't corrupted this algorithm should work perfectly. The replicator process uses this internally to perform most of the synchronization.

I'd like to think about this a bit and if necessary invite a discussion here on how other users see this if applicable?

But thank you in any case for your commitment!

Greetings
Klaus.

**Comment by CratlePeter** [comment]
Can you copy in the error that you're seeing please ?

**Comment by tachtler** [comment]
Hi,

it's in your fork, linear 529 - CAPTURE_OUTPUT="/dev/nul1"

Klaus.

> Can you copy in the error that you're seeing please ?

**Comment by tachtler** [comment]
Hello CratlePeter,

i decided NOT to merge your pull request, because I would like to have a simple script, with no need to handle incremental backups and the problems that could occur with it.

Thank you for your understanding!
Klaus.

**Pull request closed without merging**
